version: '3.8'

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
      - /app/node_modules
    depends_on:
      - server

  server:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    ports:
      - "1337:1337"
    environment:
      - MONGO_URL_DEV=mongodb://database:27017/FaceRecognitionLocal
    volumes:
      - ./server:/app
      - /app/node_modules
    depends_on:
      - database

  database:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
        - ./mongodb_volume:/data/db


